local state = require("loaded_state")
local languageRegistry = require("language_registry")
local parallax = require("parallax")
local effects = require("effects")
local utils = require("utils")


local script = {
    name = "stylegroundValueManipulator",
    displayName = "Styleground Value Manipulator",
    parameters = {
        stylegroundName = "",
        stylegroundTexture = "",
        stylegroundGroup = "",
        stylegroundTag = "",
        attribute = "",
        targetLayer = "Both",
        modifierLowerBound = 0,
        modifierUpperBound = 0,
        operation = "Set",
        applyScroll = false,
        roundToInteger = false,
        enableScript = false
    },
    fieldOrder = {
        "stylegroundName", "stylegroundTexture",
        "stylegroundGroup", "stylegroundTag",
        "attribute", "targetLayer",
        "modifierLowerBound", "modifierUpperBound",
        "operation", "applyScroll",
        "roundToInteger", "enableScript"
    },
    fieldInformation = {
        stylegroundName = {
            fieldType = "string",
            options = {
                "Parallax",
                "Planets",
                "Starfield",
                "Tentacles"
            }
        },
        stylegroundTexture = {
            fieldType = "string",
            options = {
                "mist",
                "purplesunset",
                "darkswamp",
                "northernlights",
                "vignette"
            }
        },
        attribute = {
            fieldType = "string",
            options = {
                "Position",
                "Speed",
                "Scroll",
                "Alpha",
                "X",
                "Y",
                "Speed X",
                "Speed Y",
                "Scroll X",
                "Scroll Y"
            }
        },
        targetLayer = {
            fieldType = "string",
            options = {
                "Both",
                "Foreground",
                "Background"
            },
            editable = false
        },
        operation = {
            fieldType = "string",
            options = {
                "Set",
                "Add",
                "Subtract",
                "Multiply",
                "Divide"
            },
            editable = false
        }
    },
    tooltip = "Several options for manipulating and randomizing numerical Attributes of Stylegrounds.\nOnly works on fields that take in numbers.\n\nIntentionaly made with a little friction to discourage mistakes and regret.",
    tooltips = {
        stylegroundName = "The name of the Styleground whose Attributes we'll be manipulating.\nThis Script WILL NOT run if this field is empty! Use \"*\" to target all Stylegrounds\n\nProvided is a list that contains every Vanilla Styleground that has values that can be manipulated.\nIf you want to manipulate anything that is not in this list, just write it's exact name into this field.\n\nExamples include: \"Cloudscape\", \"Digital Cascade\", and \"Boss starfield (custom)\"",
        stylegroundTexture = "When provided, This script will only run on Stylegrounds which have a Texture Attribute equal to the provided string.\nThis Script WILL NOT run if this field is empty! Use \"*\" to target all Textures\n\nProvided is a list that contains every easily accessible generic Texture in Vanilla.\n\nExamples include: \"mist\", \"purplesunset\", and \"bgs/04/bgc0\"",
        stylegroundGroup = "When provided, This script will only run on Stylegrounds that are inside a Group with a name equal to the provided string.\nThis Script WILL NOT run if this field is empty! Use \"*\" to ignore this filter.\n\nOnly works on Groups that have been named!!!!",
        stylegroundTag = "When provided, This script will only run on Stylegrounds that have a tag equal to the provided string.\nThis Script WILL NOT run if this field is empty! Use \"*\" to ignore this filter.",
        attribute = "The Styleground Attribute that we'll be manipulating.\nThis Script WILL NOT run if this field is empty!\n\nProvided is a list that contains all the Attributes for basic Parallax Stylegrounds.\nIf you want to manipulate anything that is not in this list, just write it's exact name into this field.\n\nThe first three options in this list (\"Position\", \"Speed\", and \"Scroll\") will manipulate both the X and Y components of those Attributes at the same time using the same settings.\nThis is why standalone X and Y versions of those Attributes are also provided.",
        targetLayer = "Which Styleground layers should we be targeting?\n\nDefaults to: \"Both\"",
        modifierLowerBound = "The Lowest possible number that can be chosen by the RNG\n\nDefaults to: \"0\"",
        modifierUpperBound = "The Highest possible number that can be chosen by the RNG\n\nDefaults to: \"0\"",
        operation = "What to do with the number generated by the RNG\n\nSet just REPLACES whatever value is currently in our targeted Attribute\nAll of the other options MODIFY whatever value is currently in our targeted Attribute using the number chosen by the RNG\n\nDefaults to: \"Set\"",
        applyScroll = "A highly specialized setting.\n\nIf enabled, moves stylegrounds in such a way that they end up in the same position relative to each other accounting for scroll.\nThe usecase for this is if you move an entire room in your map, and you need to move all the stylegrounds so that end up in the exact same places in the moved room.\n\nWHEN THIS SETTING IS ENABLED, THE MOVE DISTANCE YOU INPUT SHOULD BE IN TILES!!!\n\nOnly works on Parallax Stylegrounds, only works with position Attributes, and only works if Operation is set to Add!\nDoes nothing otherwise.",
        roundToInteger = "If enabled, rounds the final result of any operation we do to the nearest Integer.",
        enableScript = "This Script will only run if this box is checked.\n\nOnly run this script when you are sure of what you want, and you know what will happen when you run it.\nI can not be held accountable for mistakes made by poor use of this script."
    },
    prerun = function (args)

        if (args.enableScript == false) then
            error("\n\n\nStyleground Value Manipulator Scipt Error:\n\nEnable Script was not checked!\nThis Script will only run if this box is checked.\n\nOnly run this script when you are sure of what you want, and you know what will happen when you run it.\nI can not be held accountable for mistakes made by poor use of this script.\n\n")
        elseif (args.stylegroundName:gsub("%s+", "") == "") then
            error("\n\n\nStyleground Value Manipulator Scipt Error:\n\nThe Styleground Name field is empty!\nUse \"*\" to target all Stylegrounds.\n\n")
        elseif (args.stylegroundTexture:gsub("%s+", "") == "") then
            error("\n\n\nStyleground Value Manipulator Scipt Error:\n\nThe Styleground Texture field is empty!\nUse \"*\" to target all Textures.\n\n")
        elseif (args.stylegroundGroup:gsub("%s+", "") == "") then
            error("\n\n\nStyleground Value Manipulator Scipt Error:\n\nThe Styleground Group field is empty!\nUse \"*\" to ignore this filter.\n\n")
        elseif (args.stylegroundTag:gsub("%s+", "") == "") then
            error("\n\n\nStyleground Value Manipulator Scipt Error:\n\nThe Styleground Tag field is empty!\nUse \"*\" to ignore this filter.\n\n")
        elseif (args.attribute:gsub("%s+", "") == "") then
            error("\n\n\nStyleground Value Manipulator Scipt Error:\n\nThe Styleground Attribute field is empty!\nUse \"*\" to target all Attributes.\n\n")
        end

        if (args.enableScript == true) then
            if (args.targetLayer == "Both") or (args.targetLayer == "Foreground") then
                bisectFunction(state.map.stylesFg, args, "")
            end
            if (args.targetLayer == "Both") or (args.targetLayer == "Background") then
                bisectFunction(state.map.stylesBg, args, "")
            end
        end
    end
}

function bisectFunction(biStyle, args, parentName)
    local language = languageRegistry.getLanguage()
    local nameFilter = {}
    local textureFilter = {}
    local groupFilter = {}
    local tagFilter = {}


    --Take all the stylegrounds whos display names are roughly equal to what the player put in the Styleground Name field and add them to a table

    for _, style in ipairs(biStyle) do
        if (style._type == "parallax") then
            if (args.stylegroundName == "*") or (string.lower(args.stylegroundName) == "parallax") then
                table.insert(nameFilter, style)
            end
        elseif (style._type == "effect") then
            if (args.stylegroundName == "*") or (string.lower(args.stylegroundName) == string.lower(tostring(language.style.effects[style._name].name))) then
                table.insert(nameFilter, style)
            end
        elseif (style._type == "apply") then
            bisectFunction(style.children, args, style._name)
        end
    end


    --Take all the stylegrounds that passed the first check and add them to a second table if their texture field is equal to what the player specified

    for _, style in ipairs(nameFilter) do
        if (args.stylegroundTexture == "*") or (style.texture == args.stylegroundTexture) then
            table.insert(textureFilter, style)
        end
    end


    --Take all the stylegrounds that passed the second check and add them to a third table if their parent's name is equal to what the player specified

    for _, style in ipairs(textureFilter) do
        if (args.stylegroundGroup == "*") or (parentName ~= "" and (string.lower(args.stylegroundGroup) == string.lower(parentName))) then
            table.insert(groupFilter, style)
        end
    end


    --Take all the stylegrounds that passed the third check and add them to a fourth table if they have a Tag equal to what the player specified

    for _, style in ipairs(groupFilter) do
        if (args.stylegroundTag == "*") or (string.lower(args.stylegroundTag) == string.lower(style.tag)) then
            table.insert(tagFilter, style)
        end
    end


    --Actally randomize the Attributes now

    for _, style in ipairs(tagFilter) do

        local styleScrollX = 0
        local styleScrollY = 0

        --if a styleground is a Parallax, save it's scroll X and scroll Y values for potential later use

        if (style._type == "parallax") then
            for attribute, value in pairs(style) do

                local attributeDisplayName = string.lower(getAttributeDisplayName(style, attribute, language))

                if (attributeDisplayName == "scroll x") then
                    styleScrollX = value
                elseif (attributeDisplayName == "scroll y") then
                    styleScrollY = value
                end
            end
        end


        --Modify the Attributes

        for attribute, value in pairs(style) do

            local attributeDisplayName = string.lower(getAttributeDisplayName(style, attribute, language))

            --kjkjhksdljfahld ahhhhhhhhhhhhhh

            if type(style[attribute]) == "number" then
                if ((args.attribute == "*") or (string.lower(args.attribute) == attributeDisplayName)) then
                    style[attribute] = modifyValue(value, attributeDisplayName, styleScrollX, styleScrollY, args)
                elseif ((string.lower(args.attribute) == "position") and ((attributeDisplayName == "x") or (attributeDisplayName == "y"))) then
                    style[attribute] = modifyValue(value, attributeDisplayName, styleScrollX, styleScrollY, args)
                elseif ((string.lower(args.attribute) == "speed") and ((attributeDisplayName == "speed x") or (attributeDisplayName == "speed y"))) then
                    style[attribute] = modifyValue(value, attributeDisplayName, styleScrollX, styleScrollY, args)
                elseif ((string.lower(args.attribute) == "scroll") and ((attributeDisplayName == "scroll x") or (attributeDisplayName == "scroll y"))) then
                    style[attribute] = modifyValue(value, attributeDisplayName, styleScrollX, styleScrollY, args)
                end
            end
        end
    end
end


--Gets the Display Name of a given Attribute from a given styleground

function getAttributeDisplayName(style, attribute, language)
    local attributeDisplayName = ""

    if (style._type == "parallax") then
        attributeDisplayName = tostring(language.style.parallax.attribute[attribute])
    elseif (style._type == "effect") then
        local attributeNameLanguage = language.style.effects.attribute[attribute]

        if (attributeNameLanguage._exists) then
            attributeDisplayName = tostring(attributeNameLanguage)
        else
            attributeDisplayName = utils.humanizeVariableName(attribute)
        end
    end

    return attributeDisplayName
end


--Modifies the value of the targeted Attribute

function modifyValue(input, attributeDisplayName, styleScrollX, styleScrollY, args)

    rand = randomFloatInclusive(args.modifierLowerBound, args.modifierUpperBound)
    output = 0

    if (args.applyScroll and args.operation == "Add") then
        if (attributeDisplayName == "x") then
            output = input + (rand * 8 * styleScrollX)
        elseif (attributeDisplayName == "y") then
            output = input + (rand * 8 * styleScrollY)
        end
    elseif (args.operation == "Set") then
        output = rand
    elseif (args.operation == "Add") then
        output = input + rand
    elseif (args.operation == "Subtract") then
        output = input - rand
    elseif (args.operation == "Multiply") then
        output = input * rand
    elseif (args.operation == "Divide") then
        output = input / rand
    end

    if (args.roundToInteger) then
        output = saneRound(output)
    end

    return output
end


--RNG Tom Fuckery I stole

function randomFloatInclusive(min, max)
    rand = math.random() * 2
    return rand <= 1 and min + rand * (max - min) or randomFloatInclusive(min, max)
end


--Another function I stole from the internet, Rounds numbers like a normal person

function saneRound(num)
    if num >= 0 then return math.floor(num+.5)
    else return math.ceil(num-.5) end
end

return script