<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <AssemblyName>MintChocolateHelper</AssemblyName>
        <RootNamespace>Celeste.Mod.MintChocolateHelper</RootNamespace>
        <LangVersion>latest</LangVersion>
        <CelestePrefix Condition="'$(CelestePrefix)' == '' And Exists('..\..\..\Celeste.dll')">..\..\..</CelestePrefix>
        <CelestePrefix Condition="'$(CelestePrefix)' == ''">lib-stripped</CelestePrefix>
        <ZippedFiles>..\everest.yaml;..\bin\**\*.*;..\Audio\**\*.*;..\Dialog\**\*.*;..\Graphics\**\*.*;..\Ahorn\**\*.*;..\Loenn\**\*.*</ZippedFiles>
    </PropertyGroup>

    <!--Disable "Copy Local" for all references-->
    <ItemDefinitionGroup>
        <PackageReference PrivateAssets="all" ExcludeAssets="runtime" />
        <Reference Private="false" />
    </ItemDefinitionGroup>

    <ItemGroup>
        <!-- Add any dependency references here. -->
        <Reference Include="FemtoHelper" Private="false" />
    </ItemGroup>
    
    <ItemGroup>
        <PackageReference Include="MonoMod.RuntimeDetour" Version="25.3.1" PrivateAssets="all" ExcludeAssets="runtime" />
        <PackageReference Include="MonoMod.Patcher" Version="25.0.0-prerelease.2" />
        <PackageReference Include="CelesteAnalyzer" Version="*" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="CelesteMod.Publicizer" Version="*" CelesteAssembly="$(CelestePrefix)\Celeste.dll" />
        <Reference Include="$(CelestePrefix)\MMHOOK_Celeste.dll" Private="false" />
        <Reference Include="$(CelestePrefix)\FNA.dll" Private="false" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="lib-stripped\" />
    </ItemGroup>

    <Target Name="CopyFiles" AfterTargets="Build" Inputs="$(OutputPath)\$(AssemblyName).dll;$(OutputPath)\$(AssemblyName).pdb" Outputs="..\bin\$(AssemblyName).dll;..\bin\$(AssemblyName).pdb">
        <Copy SourceFiles="$(OutputPath)\$(AssemblyName).dll" DestinationFolder="..\bin" />
        <Copy SourceFiles="$(OutputPath)\$(AssemblyName).pdb" DestinationFolder="..\bin" />
    </Target>
    
    <PropertyGroup>
        <PathMap>$(MSBuildProjectDirectory)=MintChocolateHelper/</PathMap>
    </PropertyGroup>

    <Target Name="PackageMod" AfterTargets="CopyFiles" Condition="'$(Configuration)' == 'Release'">
        <ItemGroup>
            <FilesToPackage Include="$(ZippedFiles)" />
            <FilesToPackage Remove="@(FilesToPackage)" Condition="$([System.IO.Path]::GetFileName('%(FilesToPackage.Identity)').StartsWith('private-'))" />
        </ItemGroup>
        <PackageMod Files="@(FilesToPackage)" OutputPath="..\MintChocolateHelper.zip" />
    </Target>

    <Target Name="PrivatePackageMod" AfterTargets="CopyFiles" Condition="'$(Configuration)' == 'Release'">
        <ItemGroup>
            <PrivateFilesToPackage Include="$(ZippedFiles)" />
        </ItemGroup>
        <PrivatePackageMod Files="@(PrivateFilesToPackage)" OutputPath="..\private-MintChocolateHelper.zip" />
    </Target>

    <!-- Inline task used to create a .zip for the mod -->
    <UsingTask TaskName="PackageMod"
               TaskFactory="RoslynCodeTaskFactory"
               AssemblyFile="$(MSBuildToolsPath)\Microsoft.Build.Tasks.Core.dll" >
        <ParameterGroup>
            <Files ParameterType="Microsoft.Build.Framework.ITaskItem[]" Required="true" />
            <OutputPath ParameterType="System.String" Required="true" />
        </ParameterGroup>
        <Task>
            <Using Namespace="System.IO" />
            <Using Namespace="System.IO.Compression" />
            <Code Type="Fragment" Language="cs">
                <![CDATA[
                var projectDir = Path.Combine(@"$(ProjectDir)", ".."); // Go one level up, since we're inside the 'Source' directory
                projectDir = Uri.UnescapeDataString(projectDir);
            
                if (File.Exists(OutputPath))
                    File.Delete(OutputPath);

                using (ZipArchive zip = ZipFile.Open(OutputPath, ZipArchiveMode.Create))
                {
                    foreach (var file in Files)
                    {
                        string filePath = file.GetMetadata("FullPath");
                        string entryName = GetRelativePath(projectDir, filePath);
                        
                        zip.CreateEntryFromFile(filePath, entryName);
                    }
                }
    
                string GetRelativePath(string fromPath, string toPath)
                {
                    if (string.IsNullOrEmpty(fromPath)) throw new ArgumentNullException(nameof(fromPath));
                    if (string.IsNullOrEmpty(toPath))   throw new ArgumentNullException(nameof(toPath));
                
                    Uri fromUri = new Uri(fromPath);
                    Uri toUri = new Uri(toPath);
                
                    if (fromUri.Scheme != toUri.Scheme) { return toPath; } // path can't be made relative.
                
                    Uri relativeUri = fromUri.MakeRelativeUri(toUri);
                    string relativePath = Uri.UnescapeDataString(relativeUri.ToString());
                
                    if (toUri.Scheme.Equals("file", StringComparison.InvariantCultureIgnoreCase))
                    {
                        relativePath = relativePath.Replace(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar);
                    }
                
                    return relativePath;
                }
            ]]>
            </Code>
        </Task>
    </UsingTask>

    <UsingTask TaskName="PrivatePackageMod"
               TaskFactory="RoslynCodeTaskFactory"
               AssemblyFile="$(MSBuildToolsPath)\Microsoft.Build.Tasks.Core.dll" >
        <ParameterGroup>
            <Files ParameterType="Microsoft.Build.Framework.ITaskItem[]" Required="true" />
            <OutputPath ParameterType="System.String" Required="true" />
        </ParameterGroup>
        <Task>
            <Using Namespace="System.IO" />
            <Using Namespace="System.IO.Compression" />
            <Code Type="Fragment" Language="cs">
                <![CDATA[
                var projectDir = Path.Combine(@"$(ProjectDir)", ".."); // Go one level up, since we're inside the 'Source' directory
                projectDir = Uri.UnescapeDataString(projectDir);
            
                if (File.Exists(OutputPath))
                    File.Delete(OutputPath);

                using (ZipArchive zip = ZipFile.Open(OutputPath, ZipArchiveMode.Create))
                {
                    foreach (var file in Files)
                    {
                        string filePath = file.GetMetadata("FullPath");
                        string entryName = GetRelativePath(projectDir, filePath);
                        
                        // hi here is my terrible code to remove private- from the private files for the private loenn plugin builds
                        string directory = Path.GetDirectoryName(entryName);
                        string fileName = Path.GetFileName(entryName);
                        
                        if (fileName.StartsWith("private-", StringComparison.OrdinalIgnoreCase))
                        {
                            fileName = fileName.Substring("private-".Length);
                        }
                        
                        string privateFileName = string.IsNullOrEmpty(directory) ? fileName : directory.Replace("\\", "/") + "/" + fileName;
                        
                        zip.CreateEntryFromFile(filePath, privateFileName);
                    }
                }
    
                string GetRelativePath(string fromPath, string toPath)
                {
                    if (string.IsNullOrEmpty(fromPath)) throw new ArgumentNullException(nameof(fromPath));
                    if (string.IsNullOrEmpty(toPath))   throw new ArgumentNullException(nameof(toPath));
                
                    Uri fromUri = new Uri(fromPath);
                    Uri toUri = new Uri(toPath);
                
                    if (fromUri.Scheme != toUri.Scheme) { return toPath; } // path can't be made relative.
                
                    Uri relativeUri = fromUri.MakeRelativeUri(toUri);
                    string relativePath = Uri.UnescapeDataString(relativeUri.ToString());
                
                    if (toUri.Scheme.Equals("file", StringComparison.InvariantCultureIgnoreCase))
                    {
                        relativePath = relativePath.Replace(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar);
                    }
                
                    return relativePath;
                }
            ]]>
            </Code>
        </Task>
    </UsingTask>

</Project>
